---
title: "Assignment 2 - simple vers"
output: html_document
date: "2025-03-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install Packages 

```{r}
pacman::p_load(tidyverse, here, posterior, cmdstanr, brms, tidybayes, rstan, ggplot2, dplyr)
```

# Simulation functions 
```{r}
# probabilistic win-stay lose-shift model (with noise)
WSLS_asym_noise <- function(prev_choice, feedback, WS_weight, LS_weight, noise){
  if(feedback == 1){  # win
    if(rbinom(1, 1, WS_weight) == 1){
      choice <- prev_choice
    } else{
      choice <- 1 - prev_choice
    }
  }
  else if (feedback == 0){  # loss
    if(rbinom(1, 1, LS_weight) == 1){
      choice <- 1 - prev_choice
    } else{
      choice <- prev_choice
    }  
  }
  # introduce noise
  if(rbinom(1, 1, noise) == 1){
    choice <- rbinom(1, 1, .5)
  }
  return(choice)
}

# random agent 
random_agent <- function(rate){
  choice <- rbinom(1, 1, rate) 
  return(choice)
} 
```

# SIMULATE DATA 
```{r}
n <- 120 #number of trials 

## simulate choices by random agent (as hider)
rate <- 0.5 #bias for random agent 
random_hider <- list(choice = rep(NA, n)) #empty list of choices made by hider
for (i in 1:n){
  random_hider$choice[i] <- random_agent(rate)
}

## simulate choices made by wsls (as guesser) based on the random agent 
WS_weight <- 0.9 # probability of staying when winning
LS_weight <- 0.6 # probability of shifting when losing
noise <- 0 #no noise added 
wsls_guesser <- list(choice = rep(NA, n), #empty list of choices made by guesser
                     feedback = rep(NA, n)) #empty list for feedback for guesser

for(i in 1:n){
  if(i == 1){
    wsls_guesser$choice[i] <- random_agent(0.5) #random first choice 
  }
  if(i>1){
    if(wsls_guesser$choice[i-1] == random_hider$choice[i-1]){
      wsls_guesser$feedback[i-1] <- 1
    }
    else{
      wsls_guesser$feedback[i-1] <- 0
    }
    wsls_guesser$choice[i] <- WSLS_asym_noise(wsls_guesser$choice[i-1], 
                                              wsls_guesser$feedback[i-1], 
                                              WS_weight, LS_weight, noise)
  }
  if(i == n){
    if(wsls_guesser$choice[n] == random_hider$choice[n]){
      wsls_guesser$feedback[n] <- 1
    }
    else{
      wsls_guesser$feedback[n] <- 0
    }
  }
}

#combine data for model into list
data <- list(n = n, choice = wsls_guesser$choice, feedback =  wsls_guesser$feedback)
```


# STAN code 
```{r}
stan_model <- "
data{
  int <lower=1> n; // the number of trials (n) cannot be below 1 and should be integers
  array[n] int <lower=0, upper=1> choice; // the choice made by the guesser (WSLS) with length og n and can be ints 0 or 1
  array[n] int <lower=0, upper=1> feedback; // the feedback can either be 0 (loss) or 1 (win)
}
parameters{
  real theta_WS; // the bias for staying when winning on log odds scale
  real theta_LS; // the bias for shifting when losing on log odds scale
}

transformed parameters{
  vector[n] win_choice;  // define vector for storing the choice when winning (0 = lost on last trial)
  vector[n] lose_choice; // define vector for storing the choice when losing  (0 = lost on last trial)
  vector[n] theta;       // define vector for storing theta for each trial (probability of choosing right hand)
  
  theta[1] = logit(0.5); // theta for the first trial is 0.5 as there is no feedback from previous trial to use
  
  for (trial in 2:n){    // loop through each trial from trial 2 and define whether theta_WS or theta_LS should be used as theta
  
   if(feedback[trial-1] == 1){      // if the guesser won on the previous trial
     lose_choice[trial] = 0;        // discount theta_LS parameter when calculating theta
     
     if(choice[trial-1] == 1){      // if the guesser picked right (1) on the previous trial 
       win_choice[trial] = 1;       // use theta_WS parameter when calculating theta
     }
     else if (choice[trial-1] == 0){// if the guesser picked left (0)
       win_choice[trial] = -1;      // use theta_WS parameter when calculating theta
     }
   }
   if(feedback[trial-1] == 0){      // if the guesser lost on the previous trial  
     win_choice[trial] = 0;         // discount theta_wS parameter when calculating theta
     
     if(choice[trial-1] == 1){      // if the guesser picked right (1) on the previous trial 
       lose_choice[trial] = -1;     // use theta_LS when calculating theta
     }
     else if (choice[trial-1] == 0){// if the guesser picked left (0) on the previous trial 
       lose_choice[trial] = 1;      // use theta_LS when calculating theta 
     }
   }
   theta[trial] = theta_WS*win_choice[trial] + theta_LS*lose_choice[trial]; // for each trial theta is defined depending on the outcome of the previous trial (lose or win) 
  }
 
}

model{
  target += normal_lpdf(theta_WS | 0, 1); // prior for theta_WS 
  target += normal_lpdf(theta_LS | 0, 1); // prior for theta_LS
  
  for (trial in 1:n){
    target += bernoulli_logit_lpmf(choice[trial] | theta[trial]); // liklihood model, for each trial the choice is given the theta (as calculated in the transformed parameters chunk)
  }
}
generated quantities{
  // defining variables: theta_WS and theta_LS prior and posterior parameters on probability scales
  real<lower=0, upper=1> theta_WS_prior;
  real<lower=0, upper=1> theta_LS_prior;  
  real<lower=0, upper=1> theta_WS_posterior;  
  real<lower=0, upper=1> theta_LS_posterior;  
  
  // generating variables: theta_WS and theta_LS prior and posterior parameters on probability scales 
  theta_WS_prior = inv_logit(normal_rng(0,1)); 
  theta_LS_prior = inv_logit(normal_rng(0,1)); 
  theta_WS_posterior = inv_logit(theta_WS); 
  theta_LS_posterior = inv_logit(theta_LS); 
}
"

write_stan_file(
  stan_model, dir = "stan/", basename = "WSLSasym.stan")
```


# COMPILE MODEL 
```{r}
file <- file.path("stan/WSLSasym.stan")
mod <- cmdstan_model(file, cpp_options = list(stan_threads = TRUE))

samples <- mod$sample(
  data = data,
  seed = 123,
  refresh = 500,
  chains = 2,
  parallel_chains = 2,
  threads_per_chain = 2,
  iter_warmup = 1000,
  iter_sampling = 2000,
  max_treedepth = 20,
  adapt_delta = 0.99
)

samples$summary()
```

# PLOT PRIOR-POSTERIOR UPDATE CHECKS 
```{r}
draws_df <- as_draws_df(samples$draws())
ggplot(draws_df) +
  geom_density(aes(theta_WS_posterior), fill = "blue", alpha = 0.3) +
  geom_density(aes(theta_WS_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = WS_weight, linetype = "dashed", color = "black", size = 1) +
  ggtitle("Prior Posterior Update Checks: THETA WIN-STAY")+
  xlab("Rate") +
  ylab("Estimate Densities") +
  theme_classic()
ggsave("figs/prior_post_update_thetaWS.png")

ggplot(draws_df) +
  geom_density(aes(theta_LS_posterior), fill = "blue", alpha = 0.3) +
  geom_density(aes(theta_LS_prior), fill = "red", alpha = 0.3) +
  geom_vline(xintercept = LS_weight, linetype = "dashed", color = "black", size = 1) +
  ggtitle("Prior Posterior Update Checks: THETA LOSE-SHIFT")+
  xlab("Rate") +
  ylab("Estimate Densities") +
  theme_classic()
ggsave("figs/prior_post_update_thetaLS.png")
```


