---
title: "Assignment 3"
output: html_document
date: "2025-03-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Set up
```{r}
pacman::p_load(tidyverse, here, posterior, cmdstanr, brms, tidybayes, rstan, 
               ggplot2, dplyr, patchwork)
```


# FUNCTIONS
## Function for simulating first and group rating for one agent for given amount
of simuli (trials)
```{r}
simulating_ratings <- function(n_stim, max_rating){
  
  ratings <- list(first_rating = rep(NA, n_stim), 
                  group_rating = rep(NA, n_stim))
  
  for (i in 1:n_stim){
    # simulating the first rating based on a randomly sampled probability value
    prob <- runif(1, min = 0.001, max = 0.999) 
    ratings$first_rating[i] <- rbinom(1, (max_rating-1), prob) + 1
    
    # simulating the group rating, based on the value of the first rating 
    feedback <- (sample.int((max_rating-1), 1)-4)
    group_rating <- ratings$first_rating[i]+(feedback)
    ratings$group_rating[i] <- ifelse(group_rating<1, 1, 
                                      ifelse(group_rating>max_rating, max_rating,
                                             group_rating))
    #obs: feedback is constrained to not go outside the bounds of rating scale 
    #(0-8). we should do it in another way because this way creates uneven dist
    #of feedback values (below 0 is changed to 0 and above 8 is changed to 8, 
    #creating too many values of 0 and 8). 
  }
  return(ratings)
}
```

## Beta Binomial Agent, simulating second_rating
IWeight parameters are included in the  function, if none weighted agent weights = 1.
```{r}
betaBinomialModel <- function(alpha_prior, beta_prior, first_ratings, group_ratings, 
                              max_rating, n_stim, weight_first, weight_group) {
  #list of values 
  ratings2 <- list(second_rating = rep(NA, n_stim), 
                   expected_rate = rep(NA, n_stim), 
                   alpha_post = rep(NA, n_stim), 
                   beta_post = rep(NA, n_stim))
  #for each stimuli: 
  for (i in 1:n_stim){
    neg_first_rating <- max_rating - first_ratings[i] #the 'points' not given 
    neg_group_rating <- max_rating - group_ratings[i] #
    
    #calculate weighted information 
    first_rating_w <- first_ratings[i]*weight_first
    group_rating_w <- group_ratings[i]*weight_group
    neg_first_rating_w <- neg_first_rating*weight_first
    neg_group_rating_w <- neg_group_rating*weight_group
  
    # calculate posterior beta and alpha values
    ratings2$alpha_post[i] <- alpha_prior + first_rating_w + group_rating_w
    ratings2$beta_post[i] <- beta_prior + neg_first_rating_w + neg_group_rating_w      
    
    # calculated second rating based on first and group rating
    ratings2$expected_rate[i] <- ratings2$alpha_post[i] /(
                                        ratings2$alpha_post[i] + ratings2$beta_post[i])  

    ratings2$second_rating[i] <- rbinom(1, 7, ratings2$expected_rate[i]) + 1
  }
  return(ratings2)
}
```



# SIMULATE DATA
## Simple (non weighted) simulation
```{r}
n_stim <- 153 # number of stimuli (faces)
max_rating <- 8 # maximum possible rating
n_agents <- 10 # number of agents

ratings_all <- vector("list", n_agents) #list for first and group rating for all agents 
second_ratings_all <- vector("list", n_agents) #list for second rating for all agents 

#loop through each agent
for (a in 1:n_agents){
  ratings_all[[a]] <-  simulating_ratings(n_stim, max_rating) #simulate first and group ratings
  
  second_ratings_all[[a]] <- betaBinomialModel(alpha_prior = 1, beta_prior = 1,
                                               first_rating = ratings_all[[a]]$first_rating, 
                                               group_rating = ratings_all[[a]]$group_rating,
                                               max_rating, n_stim, 
                                               weight_first = 1, weight_group = 1)
}

#save data in STAN type of list 
data_simple <- list(n_stim = 153, 
                    n_agents = 10, 
                    max_rating = 8,
                    second_rating = matrix(unlist(do.call(rbind, second_ratings_all)[ 
                      ,"second_rating"]), byrow = T, ncol = n_agents),
                    first_rating = matrix(unlist(do.call(rbind, ratings_all)[ 
                      ,"first_rating"]), byrow = T, ncol = n_agents), 
                    group_rating =  matrix(unlist(do.call(rbind, ratings_all)[ 
                      ,"group_rating"]), byrow = T, ncol = n_agents))

```